<?php

declare(strict_types=1);

/**
 * V007__SeedPaymentTypes
 *
 * EXAMPLE future seeder — idempotent (ON DUPLICATE KEY).
 * Demonstrates: php bin/database migration:create SeedPaymentTypes --type=seed
 *
 * If seed data must change later, add V008__UpdatePaymentTypes — do not edit this file
 * after it has been applied.
 */

return [
    'type' => 'seed',
    'description' => 'Example: seed default payment types (idempotent)',
    'irreversible' => false,
    'up' => <<<'SQL'
INSERT INTO payment_types (id, code, label, is_active, sort_order) VALUES
  ('pay-cod', 'cod', 'Cash on delivery', 1, 1),
  ('pay-wa', 'whatsapp', 'WhatsApp order', 1, 2)
ON DUPLICATE KEY UPDATE
  label = VALUES(label),
  is_active = VALUES(is_active),
  sort_order = VALUES(sort_order);
SQL,
    'down' => <<<'SQL'
DELETE FROM payment_types WHERE id IN ('pay-cod', 'pay-wa');
SQL,
];
